name: Sync Facebook Ads to BigQuery

on:
  schedule:
    # 4h sáng GMT+7 = 21h UTC ngày hôm trước
    - cron: '0 21 * * *'
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  sync-fb-ads:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests google-cloud-bigquery
        
    - name: Create credentials file
      run: |
        echo '${{ secrets.GCP_CREDENTIALS }}' > application_default_credentials.json
        
    - name: Set environment variables
      run: |
        echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/application_default_credentials.json" >> $GITHUB_ENV
        
    - name: Run sync script
      env:
        FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        DATASET_ID: ${{ secrets.DATASET_ID }}
        TABLE_ID: ${{ secrets.TABLE_ID }}
        ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      run: python sync_fb_ads.py
      
    - name: Cleanup
      if: always()
      run: rm -f application_default_credentials.json
